// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6IGkFp65F1e2NiG8O_VGlBvVhXAKDKS8',
    appId: '1:542190780438:web:1ed7cc7864d6d4a93ff537',
    messagingSenderId: '542190780438',
    projectId: 'login-aae3d',
    authDomain: 'login-aae3d.firebaseapp.com',
    storageBucket: 'login-aae3d.appspot.com',
    measurementId: 'G-P6JHDJBK8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1rawbsRHV1CRiHTK-yjUanWYNuY4vWWk',
    appId: '1:542190780438:android:ef2de9eb18be0ead3ff537',
    messagingSenderId: '542190780438',
    projectId: 'login-aae3d',
    storageBucket: 'login-aae3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoYFgzimmxMBHQ5t9l6mHm_usWosHHsLU',
    appId: '1:542190780438:ios:6694974b8a4b0de53ff537',
    messagingSenderId: '542190780438',
    projectId: 'login-aae3d',
    storageBucket: 'login-aae3d.appspot.com',
    iosBundleId: 'com.example.sin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoYFgzimmxMBHQ5t9l6mHm_usWosHHsLU',
    appId: '1:542190780438:ios:c55d995cc35ecd193ff537',
    messagingSenderId: '542190780438',
    projectId: 'login-aae3d',
    storageBucket: 'login-aae3d.appspot.com',
    iosBundleId: 'com.example.sin.RunnerTests',
  );
}
